spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    continue-on-error: true

datasource:
  schema: create-schema.sql
  name: otherDataSource

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: password1